project:
  type: website

website:
  title: "Jake Blues Harmon"
  site-url: https://jakebharmon.github.io
  description: "This is Jake Harmon's personal blog."

format:
  html:
    theme: none
    minimal: true
    css: styles.css
    toc: false
    anchor-sections: false

execute:
  freeze: auto