project:
  type: website

page-layout: full

website:
  title: "Jake Blues Harmon"
  favicon: jhb_monogram_favicon_32png.png
  site-url: https://jakebharmon.github.io
  description: "This is Jake Harmon's personal blog."
  search: false
  navbar:
    left:
      - href: blog.qmd
        text: "Blog"
    right:
      - icon: github
        href: https://github.com/jakebharmon
      - icon: rss
        href: blog.xml
    collapse-below: lg
        
format:
  html:
    css: styles.css
    toc: FALSE

execute:
  freeze: auto

